services:
  ux-web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
